Feat/update eslint
americanexpress/eslint-config-amex pull request #121
Opened 2023-06-12 17:34 UTC by dogpatch626

## Description

BREAKING CHANGES: 
update to eslint-plugin-unicorn 47.0.0
* Require minimum of eslint 8 and node 16 required to fix bug in node 18

update eslint-config-prettier v8 
[all configs merged to one](https://github.com/prettier/eslint-plugin-prettier/blob/master/CHANGELOG.md#v400-2021-08-30)
Please make sure that the PR fulfills these requirements

- [ ] I checked that there aren't other open Pull Requests for the same update/change.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] Rule changes includes a comment to describe the reasoning behind the change.
- [ ] PR contains a single rule change.
    
## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [x] Dependency update

2023-06-13 13:12 UTC, smackfu commented
@dogpatch626 I think an admin will have to update the required checks to merge this.

2023-06-14 19:05 UTC, smackfu requested changes

2023-06-14 19:15 UTC, smackfu commented on package.json
>      "eslint-plugin-jest": "^24.1.3 || ^25.7.0 || ^26.0.0 || ^27.0.0",
It's not clear to me why this is required based on the breaking changes in v25:
https://github.com/jest-community/eslint-plugin-jest/releases/tag/v25.0.0

2023-06-14 19:15 UTC, smackfu commented on package.json
>      "eslint-plugin-jest": "^24.1.3 || ^25.7.0 || ^26.0.0 || ^27.0.0",
I'm using node v16.17.1

2023-06-14 20:17 UTC, dogpatch626 commented on package.json
>      "eslint-plugin-jest": "^24.1.3 || ^25.7.0 || ^26.0.0 || ^27.0.0",
Hey, appreciate you looking into this aswell. I was looking when I stumbled across this thread https://github.com/jest-community/eslint-plugin-jest/pull/940 and installed 25.1.0 and npm run test:lint seems to run fine so far. going to test a little more

2023-06-14 20:36 UTC, smackfu commented on package.json
>      "eslint-plugin-jest": "^24.1.3 || ^25.7.0 || ^26.0.0 || ^27.0.0",
Oh good call, yeah, it's not a breaking change for them to support a new major of a dependency.
https://github.com/jest-community/eslint-plugin-jest/releases/tag/v25.1.0

2023-06-15 14:46 UTC, smackfu approved these changes

2023-06-15 18:28 UTC, JAdshead approved these changes

2023-06-15 18:28 UTC, merged