Added a template for PR
americanexpress/eslint-config-amex pull request #55
Opened 2020-10-05 14:26 UTC by SvA1

Please let me know if any fields for the template are missing.

2020-10-05 14:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/americanexpress/eslint-config-amex?pullRequest=55) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/americanexpress/eslint-config-amex?pullRequest=55) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/americanexpress/eslint-config-amex?pullRequest=55) it.</sub>

2020-10-06 19:52 UTC, JAdshead requested changes
Thank you for your contribution. Please could you also reformat your commit message to follow our required commit format - https://www.conventionalcommits.org/en/v1.0.0-beta.2/#summary

2020-10-06 19:52 UTC, JAdshead commented on .github/pull_request_template.md
> +
- PR contains a single rule change
- Rule changes includes a comment to describe the reasoning behind the change

2020-10-06 19:52 UTC, JAdshead commented on .github/pull_request_template.md
> +- Have you successfully ran tests with your changes locally?
Don't think we need this
```suggestion
```

2020-10-21 16:25 UTC, nellyk commented
@SvA1  the PR looks good, could you please make the changes requested by @JAdshead

2020-10-21 19:10 UTC, SvA1 commented
> 
> 
> @SvA1 the PR looks good, could you please make the changes requested by @JAdshead

I'm sorry I can't edit this PR anymore, to add the changes I created a new PR, hope this works out

2020-10-22 12:20 UTC, nellyk commented
closing this

2020-10-22 12:20 UTC, closed without merging